server.port=9127
spring.application.name=juggle

##H2##
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:file:./console/src/main/resources/data/db_juggle;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;IGNORECASE=TRUE;AUTO_SERVER=TRUE;OLD_INFORMATION_SCHEMA=TRUE
#spring.datasource.username=sa
#spring.datasource.password=juggle
#spring.h2.console.enabled=true
#spring.h2.console.settings.web-allow-others=true
#spring.h2.console.path=/h2-console

##MySql##
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://rds260kj5i2879nym9a9o.mysql.rds.aliyuncs.com:3306/tpa-saas?useSSL=false&autoReconnect=true&characterEncoding=utf8
spring.datasource.username=tpasaasuser
spring.datasource.password=G#EYff17

##Basic Config##
#juggle.api-key=e543283fa34c4a9f9f76bcc3c3f31905

##Redis Cache##
#juggle.cache.cache-type=redis
#juggle.cache.redis.model=single
#juggle.cache.redis.address=127.0.0.1:6379
#juggle.cache.redis.password=

spring.redis.host=47.105.112.106
#spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=@Pukang_123
spring.redis.database=0

camel.worker.rest.dev.port=20888