server.port=9127
spring.application.name=juggle

##MySql##
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://rm-m5eusxajuopp63813.mysql.rds.aliyuncs.com:3306/integration-platform?useSSL=false&autoReconnect=true&characterEncoding=utf8
spring.datasource.username=integration_appuser
spring.datasource.password=pukang#2701

spring.data.redis.host=r-m5ed7cpxlntd40ym1s.redis.rds.aliyuncs.com
spring.data.redis.port=6379
spring.data.redis.password=k^8ry(3BCqp9@$tQ
spring.data.redis.database=1

camel.worker.rest.dev.port=20888
camel.server.port=30888
camel.cluster.id=prod
